# Use postgres/example user/password credentials
version: '3.9'

services:
    db:
        image: postgres_daily_prophet
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            - POSTGRES_DB: POSTGRES_DB
            - POSTGRES_USER: POSTGRES_USER
            - POSTGRES_PASSWORD: POSTGRES_PASSWORD

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    daily-prophet:
        build: .
        command: './bin/rails server'
        environment:
            - RAILS_ENV: RAILS_ENV
            - POSTGRES_HOST: POSTGRES_HOST
            - POSTGRES_DB: POSTGRES_DB
            - POSTGRES_USER: POSTGRES_USER
            - POSTGRES_PASSWORD: POSTGRES_PASSWORD
            - RAILS_MASTER_KEY: RAILS_MASTER_KEY
        volumes:
            - app-storage:/rails/storage
        depends_on:
            - db
        ports:
            - '3000:3000'

    volumes:
        postgres_data: {}
        app-storage: {}
